### ISSUE TITLE
Make Transcription work several times

### ISSUE THREAD

**Issue by GarrettBurroughs** [navidmx/AccessIDE#1]
Currently, the transcription doesn't work multiple times in a row. This needs to be fixed.

It seems to be an issue with the audio conversion, may attempt to convert the audio transcription to a promised based function to ensure completion

**Comment by navidmx** [comment]
Can't work on the output section until this is complete!

**Comment by GarrettBurroughs** [comment]
Oh no! I'll work on it ASAP

**Comment by GarrettBurroughs** [comment]
Turns out the problem was with the loading of the modules. It should now be fixed and run commands correctly
